stages:
  download:
    cmd: python digits_recognition/dataset/download.py -o ./data/raw/archive.zip
    deps:
    - digits_recognition/dataset/download.py
    outs:
    - ./data/raw/archive.zip
  extract:
    cmd: python digits_recognition/dataset/extract.py -z ./data/raw/archive.zip
      -o ./data/interim/unzipped
    deps:
    - digits_recognition/dataset/extract.py
    - ./data/raw/archive.zip
    outs:
    - ./data/interim/unzipped
  split:
    cmd: python digits_recognition/dataset/split.py -p ./data/interim/unzipped -tr ./data/processed/train_set.pkl
      -ts ./data/processed/test_set.pkl -v ./data/processed/val_set.pkl
      --split_seed 42 --validation_ratio 0.15
    deps:
    - digits_recognition/dataset/split.py
    - ./data/interim/unzipped
    outs:
    - ./data/processed/val_set.pkl
    - ./data/processed/test_set.pkl
    - ./data/processed/train_set.pkl
  train:
    cmd: python digits_recognition/modeling/train.py -t ./data/processed/train_set.pkl
      -v ./data/processed/val_set.pkl -m ./models/digit_classifier.pth 
      --patience 10 --epochs 100 --learning_rate 0.001 --weight_decay 1e-3 --random_seed 42
      --batch_size 64 --polynomial_scheduler_power 4.0
    deps:
    - digits_recognition/modeling/classifier.py
    - digits_recognition/modeling/train.py
    - digits_recognition/load_dataset.py
    - digits_recognition/mlflow_setup.py
    - ./data/processed/val_set.pkl
    - ./data/processed/train_set.pkl
    outs:
    - ./models/digit_classifier.pth
  evaluate:
    cmd: python digits_recognition/modeling/evaluate.py -t ./data/processed/test_set.pkl
      -m ./models/digit_classifier.pth --batch_size 64
    deps:
    - digits_recognition/modeling/evaluate.py
    - digits_recognition/modeling/classifier.py
    - digits_recognition/load_dataset.py
    - digits_recognition/mlflow_setup.py
    - ./data/processed/test_set.pkl
    - ./models/digit_classifier.pth