stages:
  download:
    cmd: python digits_recognition/experimentation/dataset/download.py
      --out_path ${data.raw.archive}
      --url ${data.url}
    deps:
    - digits_recognition/experimentation/dataset/download.py
    outs:
    - ${data.raw.archive}
  extract:
    cmd: python digits_recognition/experimentation/dataset/extract.py
      --zip_path ${data.raw.archive}
      --out_path ${data.interim.unzipped}
    deps:
    - digits_recognition/experimentation/dataset/extract.py
    - ${data.raw.archive}
    outs:
    - ${data.interim.unzipped}
  check:
    cmd: python digits_recognition/experimentation/dataset/check.py
      --path ${data.interim.unzipped}
      --image_width ${data.meta.images.width}
      --image_height ${data.meta.images.height}
      --classes ${data.meta.classes.count}
    deps:
    - digits_recognition/experimentation/dataset/check.py
    - ${data.interim.unzipped}
  convert:
    cmd: python digits_recognition/experimentation/dataset/convert.py
      --path ${data.interim.unzipped}
      --train_set_path ${data.interim.train_set}
      --test_set_path ${data.processed.test_set}
    deps:
    - digits_recognition/experimentation/dataset/convert.py
    - ${data.interim.unzipped}
    outs:
    - ${data.processed.test_set}
    - ${data.interim.train_set}
  validation_split:
    cmd: python digits_recognition/experimentation/dataset/validation_split.py
      --dataset_path ${data.interim.train_set}
      --train_set_path ${data.processed.train_set}
      --val_set_path ${data.processed.val_set}
      --split_seed ${data.split.random_seed}
      --validation_ratio ${data.split.ratio}
    deps:
    - digits_recognition/experimentation/dataset/validation_split.py
    - ${data.interim.train_set}
    outs:
    - ${data.processed.val_set}
    - ${data.processed.train_set}
  train:
    cmd: python digits_recognition/experimentation/modeling/train.py 
      --train_set_path ${data.processed.train_set}
      --val_set_path ${data.processed.val_set}
      --model_path ${model}
      --patience ${training.patience}
      --epochs ${training.epochs}
      --learning_rate ${training.learning_rate}
      --weight_decay ${training.weight_decay}
      --random_seed ${training.random_seed}
      --batch_size ${training.batch_size}
      --polynomial_scheduler_power ${training.polynomial_scheduler_power}
      --image_width ${data.meta.images.width}
      --image_height ${data.meta.images.height}
      --image_channels ${data.meta.images.channels}
      --classes ${data.meta.classes.count}
      --repo_owner ${dagshub.repo_owner}
      --repo_name ${dagshub.repo_name}
      --experiment_name ${mlflow.experiment_name}
    deps:
    - digits_recognition/experimentation/modeling/classifier.py
    - digits_recognition/experimentation/modeling/train.py
    - ${data.processed.val_set}
    - ${data.processed.train_set}
    outs:
    - ${model}
  evaluate:
    cmd: python digits_recognition/experimentation/modeling/evaluate.py
      --test_set_path ${data.processed.test_set}
      --model_path ${model}
      --batch_size ${evaluation.batch_size}
      --image_width ${data.meta.images.width}
      --image_height ${data.meta.images.height}
      --image_channels ${data.meta.images.channels}
      --classes ${data.meta.classes.count}
      --repo_owner ${dagshub.repo_owner}
      --repo_name ${dagshub.repo_name}
      --experiment_name ${mlflow.experiment_name}
    deps:
    - ${data.processed.test_set}
    - ${model}