model: ./models/digit_classifier.pth

data:
  url: https://www.kaggle.com/api/v1/datasets/download/hojjatk/mnist-dataset
  split:
    random_seed: 42
    ratio: 0.15
  meta:
    images:
      width: 28
      height: 28
      channels: 1 
    classes:
      count: 10
  raw:
    archive: ./data/raw/archive.zip
  interim:
    unzipped: ./data/interim/unzipped
    train_set: ./data/interim/train_set.pkl
  processed:
    test_set: ./data/processed/test_set.pkl
    train_set: ./data/processed/train_set.pkl
    val_set: ./data/processed/val_set.pkl

evaluation:
  batch_size: 64
  random_seed: 42

training:
  epochs: 1
  batch_size: 64
  patience: 20
  learning_rate: 0.001
  weight_decay: 1.5e-3
  random_seed: 42
  polynomial_scheduler_power: 2.0

dagshub:
  repo_owner: GianmarcoTurchiano
  repo_name: Digits-Recognition

mlflow:
  model_name: GiaNet
  experiment_name: '"Modified LeNet-5 model"'